{
  wayland.windowManager.hyprland = {
    enable = true;
    extraConfig = ''
              # AUTOGENERATED HYPR CONFIG.
          # PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
          # OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
          # #######################################################################################


          # This is an example Hyprland config file.
          # Refer to the wiki for more information.
          # https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

          # Please note not all available settings / options are set here.
          # For a full list, see the wiki

          # You can split this configuration into multiple files
          # Create your files separately and then link them to this file like this:
          # source = ~/.config/hypr/myColors.conf

          ################
          ### MONITORS ###
          ################

          # See https://wiki.hyprland.org/Configuring/Monitors/
          monitor = eDP-1, 2256x1504@60, auto, 1.175
          monitor = DP-1 , preferred, auto, 1
          monitor = DP-2 , preferred, auto, 1
          monitor = DP-3 , preferred, auto, 1
          monitor = , preferred, auto, 1

          ###################
          ### MY PROGRAMS ###
          ###################

          # See https://wiki.hyprland.org/Configuring/Keywords/

          # Set programs that you use
          $terminal = kitty
          $EDITOR = nvim
          $fileManager = kitty --class=yazi -e 'yazi'
          $menu = rofi -show drun 


          #################
          ### AUTOSTART ###
          #################

          # Autostart necessary processes (like notifications daemons, status bars, etc.)
          # Or execute your favorite apps at launch like this:

           exec-once = swaync & libnotify
           exec-once = hyprpaper
           exec-once = [workspace 2 silent] vesktop
           exec-once = hypridle
           exec-once = firefox
           exec-once = Bitwarden
           exec-once = openrgb --profile pink
           exec-once = [workspace 3 silent] kitty --class=microfetch -e microfetch
           exec-once = [workspace 4 silent] kitty -e btop
           exec-once = hyprlock
           exec-once = hyprctl setcursor Nordzy-catppuccin-mocha-dark 30
           exec = gsettings set org.gnome.desktop.interface color-scheme Nordic-darker   # for GTK4 apps
           exec = gsettings set org.gnome.desktop.interface gtk-theme Nordic-darker   # for GTK3 apps
           exec = gsettings set org.gnome.desktop.wm.preferences theme Nordic-darker





          #############################
          ### ENVIRONMENT VARIABLES ###
          #############################

          # See https://wiki.hyprland.org/Configuring/Environment-variables/
          env = QT_QPA_PLATFORMTHEME,qt6ct   # for Qt apps
          env = GTK_THEME,Nordic-darker
          env = HYPRCURSOR_THEME,"Nordzy-catppuccin-mocha-dark"
          env = HYPRCURSOR_SIZE,30
          env = GDK_SCALE,2
          env = XDG_MENU_PREFIX,plasma


          xwayland {
              force_zero_scaling = true
              }

          #####################
          ### LOOK AND FEEL ###
          #####################

          # Refer to https://wiki.hyprland.org/Configuring/Variables/

          # https://wiki.hyprland.org/Configuring/Variables/#general
          general {
              gaps_in = 5
              gaps_out = 20

              border_size = 2

              # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
              col.active_border =  rgb(255,20,147) rgb(255,182,193) 45deg
              col.inactive_border = rgba(595959aa)

              # Set to true enable resizing windows by clicking and dragging on borders and gaps
              resize_on_border = false

              # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
              allow_tearing = false

              layout = dwindle
          }

          # https://wiki.hyprland.org/Configuring/Variables/#decoration
          decoration {
              rounding = 10

              # Change transparency of focused and unfocused windows
              active_opacity = 1.0
              inactive_opacity = 1.0

          #    drop_shadow = true
          #    shadow_range = 4
          #    shadow_render_power = 3
          #    col.shadow = rgba(1a1a1aee)

              # https://wiki.hyprland.org/Configuring/Variables/#blur
              blur {
                  enabled = true
                  size = 3
                  passes = 1

                  vibrancy = 0.1696
              }
          }

          # https://wiki.hyprland.org/Configuring/Variables/#animations
          animations {
              enabled = true

              # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

              bezier = myBezier, 0.05, 0.9, 0.1, 1.05

              animation = windows, 1, 7, myBezier
              animation = windowsOut, 1, 7, default, popin 80%
              animation = border, 1, 10, default
              animation = borderangle, 1, 8, default
              animation = fade, 1, 7, default
              animation = workspaces, 1, 6, default
          }

          # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
          dwindle {
              pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
              preserve_split = true # You probably want this
          }

          # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
          master {
              new_status = master
          }

          # https://wiki.hyprland.org/Configuring/Variables/#misc
          misc {
              force_default_wallpaper = 1 # Set to 0 or 1 to disable the anime mascot wallpapers
              disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
              enable_anr_dialog = false
          }


          #############
          ### INPUT ###
          #############

          # https://wiki.hyprland.org/Configuring/Variables/#input
          input {
              kb_layout = us
              kb_variant =
              kb_model =
              kb_options =
              kb_rules =

              follow_mouse = 1

              sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

              touchpad {
                  natural_scroll = false
              }
          }


          # Example per-device config
          # See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
          device {
              name = epic-mouse-v1
              sensitivity = -0.5
          }


          ####################
          ### KEYBINDINGSS ###
          ####################

          # See https://wiki.hyprland.org/Configuring/Keywords/
          $mainMod = SUPER # Sets "Windows" key as main modifier

          # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
          bind = $mainMod, F, exec, hyprshot -m region
          bind = $mainMod, W, exec, wifi-menu
          bind = $mainMod, T, exec, rofi-bluetooth
          bind = $mainMod, E, exec, $fileManager
          bind = $mainMod CTRL, E, togglefloating
          bind = $mainMod, X, movewindow, mon:+1
          bind = $mainMod, B, exec, pkill waybar || waybar
          bind = $mainMod, Q, exec, $terminal
          bind = $mainMod CTRL, Q, exec, kitty --class=floatingkitty
          bind = $mainMod CTRL, C, killactive,
          bind = $mainMod, V, fullscreen,
          bind = $mainMod, R, exec, $menu
          bind = $mainMod, P, pseudo, # dwindle
          bind = $mainMod, I, togglesplit, # dwindle

          bindl = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
          bind = ,xf86audioraisevolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
          bind = ,xf86audiolowervolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
          bind = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-
          bind = ,XF86MonBrightnessUp, exec, brightnessctl s +10%

          #lockscreen
          bind = $mainMod SHIFT, L, exec, hyprlock

          # Move focus with mainMod + arrow keys
          bind = $mainMod, H, movefocus, l
          bind = $mainMod, L, movefocus, r
          bind = $mainMod, K, movefocus, u
          bind = $mainMod, J, movefocus, d

          # Switch workspaces with mainMod + [0-9]
          bind = $mainMod, 1, workspace, 1
          bind = $mainMod, 2, workspace, 2
          bind = $mainMod, 3, workspace, 3
          bind = $mainMod, 4, workspace, 4
          bind = $mainMod, 5, workspace, 5
          bind = $mainMod, 6, workspace, 6
          bind = $mainMod, 7, workspace, 7
          bind = $mainMod, 8, workspace, 8
          bind = $mainMod, 9, workspace, 9
          bind = $mainMod, 0, workspace, 10

          # Move active window to a workspace with mainMod + SHIFT + [0-9]
          bind = $mainMod SHIFT, 1, movetoworkspace, 1
          bind = $mainMod SHIFT, 2, movetoworkspace, 2
          bind = $mainMod SHIFT, 3, movetoworkspace, 3
          bind = $mainMod SHIFT, 4, movetoworkspace, 4
          bind = $mainMod SHIFT, 5, movetoworkspace, 5
          bind = $mainMod SHIFT, 6, movetoworkspace, 6
          bind = $mainMod SHIFT, 7, movetoworkspace, 7
          bind = $mainMod SHIFT, 8, movetoworkspace, 8
          bind = $mainMod SHIFT, 9, movetoworkspace, 9
          bind = $mainMod SHIFT, 0, movetoworkspace, 10


          # Example special workspace (scratchpad)
          bind = $mainMod, S, togglespecialworkspace, magic
          bind = $mainMod SHIFT, S, movetoworkspace, special:magic

          # Scroll through existing workspaces with mainMod + scroll
          bind = $mainMod, mouse_down, workspace, e+1
          bind = $mainMod, mouse_up, workspace, e-1

          # Move/resize windows with mainMod + LMB/RMB and dragging
          bindm = $mainMod, mouse:272, movewindow
          bindm = $mainMod, mouse:273, resizewindow
          bind = CTRL, Z, fullscreen, 1

          ##############################
          ### WINDOWS AND WORKSPACES ###
          ##############################

          # Example windowrule v1

        windowrule {
          name = windowrule-1
          float = on
          match:class = floatingkitty
        }

        windowrule {
          name = windowrule-2
          size = (monitor_w*0.45) (monitor_h*0.45)
          match:class = floatingkitty
          match:float = 0
        }

        windowrule {
          name = windowrule-3
          workspace = 1
          match:class = ^firefox$
        }


            # windowrule v2
      windowrule {
        name = windowrule-4
        float = on
        match:class = org.pulseaudio.pavucontrol
        match:title = Volume Control
      }
      windowrule {
        name = windowrule-5
        float = on
        size = (monitor_w*0.45) (monitor_h*0.45)
        move = (1000) (80)
        match:class = bluetui
      }


      windowrule {
        name = windowrule-6
        float = on
        size = (monitor_w*0.45) (monitor_h*0.45)
        move = (1000) (80)
        match:class = nmtui
      }


      windowrule {
        name = windowrule-7
        float = on
        size = (monitor_w*0.25) (monitor_h*0.25)
        move = (1000) (80)
        match:title = Volume Control
      }


      windowrule {
        name = windowrule-8
        float = on
        size = (monitor_w*0.25) (monitor_h*0.25)
        move = (cursor_x-(window_w*0.5)) (cursor_y-(window_h* - 0.5))
        match:title = Proton VPN
      }


      windowrule {
        name = windowrule-9
        float = on
        size = (monitor_w*0.45) (monitor_h*0.45)
        move = (980) (400)
        match:class = yazi
      }


      windowrule {
        name = windowrule-10
        float = on
        size = (monitor_w*0.5) (monitor_h*0.4)
        move = (100) (100)
        match:class = Bitwarden
      }

     windowrule {
          name = windowrule-11
          float = on
          size = (monitor_w*0.3) (monitor_h*0.3)
          match:title = VeraCrypt
        }


      windowrule {
          name = windowrule-12
          move = (min(max((monitor_w*1),0),monitor_w-window_w)) (min(max((monitor_h*0.6),0),monitor_h-window_h)) (min(max(title:VeraCrypt,0),monitor_h-window_h))

        }

      windowrule {
          name = windowrule-13
          float = on
          size = (monitor_w*0.4) (monitor_h*0.4)
          move = (400) (670)
          match:class = microfetch
        }


        windowrule {
          name = windowrule-14
          suppress_event = maximize
          match:class = .* # You'll probably like this.
        }


        windowrule {
          name = windowrule-15
          tile = true
          match:class = steam
          }


    '';
  };
}
